name: deploy
on:
  push: 
    branches: [ main ]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          node-version: '20'
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - run: npm run deploy

